Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]
  myDNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref 'HostedZoneResource' (fidor.com)
      Comment: DNS name for my instance. (wordpress.eastus.fidor.com)
      Name: !Join ['', [!Ref 'Ec2Instance', ., !Ref 'AWS::Region', ., !Ref 'HostedZone', .]]
      Type: A
      TTL: '900'
      ResourceRecords:
      - !GetAtt Ec2Instance.PublicIp
